baseURL = "https://vivian6f2.github.io/"
languageCode = "en-us"
title = "Ting-Hsuan Lin"
theme = "minimal"

[params]
    author = "Ting-Hsuan Lin"
    description = ""
    githubUsername = "vivian6f2"
    accent = "#84C1FF"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "tomorrow" #"tomorrow" #"color-brewer"#"atelier-sulphurpool-light"
    highlightLanguages = ["python", "javascript", "c++", "json", "swift", "php", "sql", "html"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
	url = "/resume/"
	name = "Resume"
	weight = 4


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:6f2vivian@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/vivian6f2/"
    name = "github"
    weight = 2

# [[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/ting-hsuan-lin-829138133/"
    name = "linkedin"
    weight = 3

# [[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
